-- ==========================================================================
-- KR CoreOS - Location Groups v1.2.0 B42 (Server)
-- Copyright (C) 2026 D4RK-C0MP4N1. Licensed under the MIT License (see LICENSE).
-- ==========================================================================
--
-- Defines the location groups (ProceduralDistributions containers) that the
-- KR mods use to register their items.
--
-- All names verified against ProceduralDistributions.lua from the B42.20
-- install (full container coverage: every B42.20 loot table is grouped). Names that don't exist in future versions are skipped silently in
-- KRCore_Server (processDistributions).
--
-- KRCore.COMBO (at the end) defines combined groups: a name that expands to
-- the union of several KRCore.LOC groups, with automatic dedupe. Used just
-- like a normal group in KRCore.dist.add().
-- ==========================================================================

KRCore.LOC = {

    -- =========================================================
    -- MILITARY
    -- Military, police, prison and security storage
    -- =========================================================
    MILITARY = {
        "ArmyStorageElectronics",
        "ArmyStorageOutfit",
        "ArmyHangarTools",
        "ArmyHangarMechanics",
        "ArmyStorageMedical",
        "ArmySurplusTools",
        "ArmySurplusMisc",
        "ArmySurplusCases",
        "ArmySurplusBackpacks",
        "ArmyBunkerLockers",
        "ArmyBunkerStorage",
        "PoliceStorageMechanics",
        "PoliceLockers",
        "FireStorageTools",
        "SecurityLockers",
        "PrisonGuardLockers",
        "RangerLockers",
        "ArmySurplusSnacks",
        "ArmySurplusWater",
        "FireDeptLockers",
        "JockeyLockers",
        "PoliceCaptainCabinet",
        "PoliceEvidence",
        "PrisonCellRandom",
        "PrisonCellRandomClassy",
        "PrisonIntakeLockers",
        "PrisonIntakePersonalObjects",
        "PrisonRiotStorage",
        "SecurityStorage",
        "WildWestSheriffLocker",
    },

    -- =========================================================
    -- SURVIVAL
    -- Camping, hunting and survival-gear stores
    -- =========================================================
    SURVIVAL = {
        "SurvivalGear",
        "CampingStoreGear",
        "CampingStoreTools",
        "CampingStoreLighting",
        "CampingStoreCases",
        "CampingStoreBackpacks",
        "CampingLockers",
        "Hunter",
        "HuntingLockers",
        "RangerTools",
        "CampingStoreSleepingBags",
        "CampingStoreTents",
        "FishingLockers",
        "Hiker",
        "RangerStorageTraps",
        "Trapper",
    },

    -- =========================================================
    -- ELECTRONIC
    -- Electronics stores and tech containers
    -- =========================================================
    ELECTRONIC = {
        "ElectronicStoreAppliances",
        "ElectronicStoreHAMRadio",
        "ElectronicStoreMisc",
        "ElectronicStoreCases",
        "ElectronicStoreComputers",
        "ElectronicStorePhones",
        "ElectronicStoreLights",
        "GigamartHouseElectronics",
        "GigamartLightbulb",
        "StoreShelfElectronics",
        "CrateGenerator",
        "GeneratorRoom",
        "ElectricianTools",
        "WireFactoryElectric",
        "BookstoreComputer",
        "CarLightbars",
        "CrateComputer",
        "CrateTV",
        "CrateTVWide",
        "CyberCafeDesk",
        "CyberCafeFilingCabinet",
        "ElectronicStoreMagazines",
        "ElectronicStoreMusic",
        "LibraryComputer",
        "RadioFactoryComponents",
        "UniversityDesk_Computer",
        "UniversityFilingCabinet_Computer",
        "UniversityLibraryComputer",
    },

    -- =========================================================
    -- MEDICAL
    -- Medical and hospital storage
    -- =========================================================
    MEDICAL = {
        "MedicalStorageDrugs",
        "MedicalStorageTools",
        "MedicalClinicTools",
        "HospitalLockers",
        "ArmyBunkerMedical",
        "SafehouseMedical",
        "AmbulanceDriverTools",
        "BinHospital",
        "BookstoreMedical",
        "DerelictHouseDrugs",
        "DrugLabMoney",
        "DrugLabSupplies",
        "DrugShackDrugs",
        "DrugShackMisc",
        "DrugShackTools",
        "DrugShackWeapons",
        "HospitalMagazineRack",
        "HospitalRoomCleaning",
        "HospitalRoomCounter",
        "HospitalRoomShelves",
        "LaundryHospital",
        "LibraryMedical",
        "MedicalCabinet",
        "MedicalClinicDrugs",
        "MedicalOfficeBooks",
        "MedicalOfficeCounter",
        "MedicalOfficeDesk",
        "NurseTools",
        "OptometristDesk",
        "OptometristGlasses",
        "PharmacyCosmetics",
        "PharmacyGlasses",
        "SafehouseMedical_Late",
        "SafehouseMedical_Mid",
        "StoreShelfMedical",
        "UniversityDesk_Medical",
        "UniversityFilingCabinet_Medical",
        "UniversityLibraryMedical",
    },

    -- =========================================================
    -- INDUSTRIAL
    -- Workshops, factories and industrial storage
    -- =========================================================
    INDUSTRIAL = {
        "FactoryLockers",
        "GarageMechanics",
        "GigamartTools",
        "ToolStoreTools",
        "ToolStoreMisc",
        "ToolFactoryTools",
        "GarageTools",
        "MetalShopTools",
        "WeldingWorkshopTools",
        "CabinetFactoryTools",
        "WireFactoryTools",
        "RailYardTools",
        "BarnTools",
        "ConstructionWorkerTools",
        "AnthropologyDisplayTools",
        "BatFactoryBats",
        "BlacksmithLiterature",
        "BlacksmithMolds",
        "BlacksmithTools",
        "BurglarTools",
        "CarpenterTools",
        "CarpentryBooks",
        "CarvingWorkshopMaterials",
        "CarvingWorkshopTools",
        "ChefTools",
        "ClockRepairTools",
        "CobblerTools",
        "CrateBlacksmithing",
        "CrateCarpentry",
        "CrateIndustrialDye",
        "CrateIndustrialSinks",
        "CrateMetalwork",
        "DoctorTools",
        "DogFoodFactoryBags",
        "DogFoodFactoryBones",
        "DogFoodFactoryCans",
        "DogFoodFactoryEquipment",
        "EngineerTools",
        "FarmerTools",
        "FiremanTools",
        "FishermanTools",
        "ForestFireTools",
        "FryFactoryPotatoes",
        "FurnitureFactoryTools",
        "GardenerTools",
        "GlassWorkshopTools",
        "GolfFactoryTools",
        "JanitorTools",
        "JerkyFactoryCrate",
        "JerkyFactoryMeat",
        "JerkyFactorySpices",
        "JerkyFactoryTools",
        "JewelerTools",
        "KnappingTools",
        "KnifeFactoryHandles",
        "KnifeFactoryMeatCleaver",
        "KnifeFactoryMeatCleaverBlades",
        "KnifeFactorySushiKnife",
        "KnifeFactoryTools",
        "LeatherworkingTools",
        "LoggingFactoryTools",
        "MannequinFactoryPaint",
        "MannequinFactoryTools",
        "MedievalTools",
        "MetalWorkerTools",
        "MorgueTools",
        "PaintStudioTools",
        "PoliceStateTools",
        "PoliceTools",
        "PotteryStudioTools",
        "RailYardSpikes",
        "SewingStoreTools",
        "TailoringTools",
        "ToolCabinetFarming",
        "ToolFactoryBarStock",
        "ToolFactoryHandles",
        "ToolFactoryIngots",
        "ToolFactorySawBlades",
        "ToolStoreAccessories",
        "ToolStoreBooks",
        "ToolStoreCarpentry",
        "ToolStoreFarming",
        "ToolStoreHandles",
        "ToolStoreKeymaking",
        "ToolStoreMetalwork",
        "ToolStorePaint",
        "WeldingWorkshopFuel",
        "WeldingWorkshopMetal",
        "WildWestBlacksmith",
        "WireFactoryBarbed",
        "WireFactoryBasic",
    },

    -- =========================================================
    -- MECHANIC
    -- Auto shops and car-part stores
    -- (ideal for car-battery-related items)
    -- =========================================================
    MECHANIC = {
        "CarSupplyBatteries",
        "CarSupplyTools",
        "CarSupplyGasCans",
        "MechanicShelfElectric",
        "MechanicShelfTools",
        "MechanicShelfMisc",
        "MechanicSpecial",
        "MechanicTools",
        "CrateMechanics",
        "StoreShelfMechanics",
        "ToolCabinetMechanics",
        "GarageMechanics",
        "CarBrakesModern1",
        "CarBrakesModern2",
        "CarBrakesModern3",
        "CarBrakesNormal1",
        "CarBrakesNormal2",
        "CarBrakesNormal3",
        "CarDealerDesk",
        "CarDealerFilingCabinet",
        "CarMufflerModern1",
        "CarMufflerModern2",
        "CarMufflerModern3",
        "CarMufflerNormal1",
        "CarMufflerNormal2",
        "CarMufflerNormal3",
        "CarSupplyLiterature",
        "CarSupplyMagazines",
        "CarSuspensionModern1",
        "CarSuspensionModern2",
        "CarSuspensionModern3",
        "CarSuspensionNormal1",
        "CarSuspensionNormal2",
        "CarSuspensionNormal3",
        "CarTiresModern1",
        "CarTiresModern2",
        "CarTiresModern3",
        "CarTiresNormal1",
        "CarTiresNormal2",
        "CarTiresNormal3",
        "CarWindows1",
        "CarWindows2",
        "CarWindows3",
        "FireStorageMechanics",
        "GarageCarpentry",
        "GarageMetalwork",
        "GasStorageCombo",
        "GasStorageMechanics",
        "LaboratoryGasStorage",
        "MechanicShelfBooks",
        "MechanicShelfBrakes",
        "MechanicShelfMufflers",
        "MechanicShelfSuspension",
        "MechanicShelfWheels",
    },

    -- =========================================================
    -- CRATES
    -- Generic storage crates
    -- =========================================================
    CRATES = {
        "CrateElectronics",
        "CrateFishing",
        "CrateCamping",
        "CrateFarming",
        "CrateBatteries",
        "CrateTools",
        "CrateToolsOld",
        "CrateMechanics",
        "CrateMetalLockers",
        "CrateOfficeSupplies",
        "GroceryStorageCrate1",
        "GroceryStorageCrate2",
        "GroceryStorageCrate3",
        "CrateBakingSoda",
        "CrateBeer",
        "CrateCanning",
        "CrateChromeSinks",
        "CrateClayBags",
        "CrateCoke",
        "CrateConesIceCream",
        "CrateCornflour",
        "CrateEggs",
        "CrateEspressoMachine",
        "CrateFlintNodules",
        "CrateGravyMix",
        "CrateGreenOven",
        "CrateGreyOven",
        "CrateHotsauce",
        "CrateHumanitarian",
        "CrateLargeStone",
        "CrateLongStick",
        "CrateMaps",
        "CrateMapsLarge",
        "CrateMetalBars",
        "CrateModernOven",
        "CrateNapkins",
        "CrateOilOlive",
        "CratePaint",
        "CratePancakeMix",
        "CratePaperBagJays",
        "CratePaperBagSpiffos",
        "CratePaperNapkins",
        "CratePlasticTrays",
        "CrateRedOven",
        "CrateRice",
        "CrateSandBags",
        "CrateSodaCans",
        "CrateSoysauce",
        "CrateStoneBlocks",
        "CrateStones",
        "CrateTea",
        "CrateTomatoPaste",
        "CrateToys",
        "CrateWallets",
        "CrateWallpaper",
        "CrateWaterBottle",
        "CrateWaterDispenserBottle",
        "CrateWhiteSinks",
        "CrateWine",
    },

    -- =========================================================
    -- SPECIAL
    -- Special and rare locations (includes mid/late-phase safehouses:
    -- curated loot the engine places in shelters)
    -- =========================================================
    SPECIAL = {
        "SafehouseArmor",
        "SafehouseArmor_Mid",
        "SafehouseArmor_Late",
        "SafehouseLighting",
        "SafehouseLighting_Late",
        "PostOfficeBoxes",
        "PawnShopCases",
        "PawnShopTools",
        "GunStoreCounter",
        "GunStoreCases",
        "SchoolLockers",
        "DerelictHouseCrime",
        "DerelictHouseParty",
        "DerelictHouseSquatter",
        "Locker",
        "LockerClassy",
        "PawnShopKnives",
        "PlankStashGold",
        "PlankStashMisc",
        "PlankStashMoney",
        "PoolLockers",
        "SafehouseBin",
        "SafehouseBin_Late",
        "SafehouseBin_Mid",
        "SafehouseFireplace",
        "SafehouseFireplace_Late",
        "SafehouseTraps",
        "SeasonalWorkerLockers",
    },

    -- =========================================================
    -- STORES
    -- General stores and big-box stores
    -- =========================================================
    STORES = {
        "GigamartHousewares",
        "GigamartBBQ",
        "WildWestGeneralStore",
        "GardenStoreMisc",
        "GardenStoreTools",
        "GrillStoreBlackBBQ",
        "GrillStoreRedBBQ",
        "FishingStoreGear",
        "FishingStoreBait",
        "ArtStoreOther",
        "ArtStorePaper",
        "ArtStorePen",
        "CrateSpiffoMerch",
        "DepartmentStoreWatches",
        "GasStoreEmergency",
        "GasStoreSpecial",
        "GiftStoreCards",
        "GiftStoreFancy",
        "GiftStoreToys",
        "Gifts",
        "GigamartBakingMisc",
        "GigamartBreakfast",
        "GigamartDryGoods",
        "GigamartFarming",
        "GigamartPaper",
        "GigamartPots",
        "GigamartToys",
        "HolidayStuff",
        "StoreCounterBags",
        "StoreCounterBagsFancy",
        "StoreCounterBagsPaper",
        "StoreCounterStrawsNapkins",
        "StoreDisplayWatches",
        "StoreShelfBeer",
        "StoreShelfCombo",
        "StoreShelfDrinks",
        "StoreShelfWine",
        "WildWestBarCounter",
        "WildWestBarShelf",
        "WildWestShelves",
        "WildWestSouveniers",
    },

    -- =========================================================
    -- BREAKROOM
    -- Break rooms and offices
    -- =========================================================
    BREAKROOM = {
        "BreakRoomCounter",
        "BreakRoomShelves",
        "OfficeShelfSupplies",
    },

    -- =========================================================
    -- BAR
    -- Bars, theatres and entertainment
    -- =========================================================
    BAR = {
        "BarCounterMisc",
        "BarShelfLiquor",
        "TheatreDrinks",
        "TheatreSnacks",
        "BarCounterGlasses",
        "BarCounterWeapon",
        "BarCrateDarts",
        "BarCratePool",
    },

    -- =========================================================
    -- FRIDGE
    -- Residential and commercial refrigerators
    -- =========================================================
    FRIDGE = {
        "FridgeGeneric",
        "FridgeRich",
        "FridgeOther",
        "FridgeTrailerPark",
        "FridgeBeer",
        "FridgeBottles",
        "FridgeBreakRoom",
        "FridgeDrugLab",
        "FridgeFarmStorage",
        "FridgeGarage",
        "FridgeMedical",
        "FridgeOffice",
        "FridgeSnacks",
        "FridgeSoda",
        "FridgeVIPLounge",
        "FridgeWater",
        "FridgeHoarder",
        "FridgeHunter",
        "BackstageFridge",
        "BakeryKitchenFridge",
        "BandPracticeFridge",
        "BurgerKitchenFridge",
        "CafeDiningFridge",
        "CafeKitchenFridge",
        "CafeteriaKitchenFridge",
        "CatfishKitchenFridge",
        "ChineseKitchenFridge",
        "CrepeKitchenFridge",
        "DeepFryKitchenFridge",
        "DinerKitchenFridge",
        "FishChipsKitchenFridge",
        "HospitalRoomFridge",
        "ItalianKitchenFridge",
        "JaysKitchenFridge",
        "JuiceStandFridge",
        "MexicanKitchenFridge",
        "MotelFridge",
        "NolansFridge",
        "PizzaKitchenFridge",
        "RestaurantKitchenFridge",
        "SafehouseFridge",
        "SafehouseFridge_Mid",
        "SafehouseFridge_Late",
        "SeafoodKitchenFridge",
        "SpiffosKitchenFridge",
        "SushiKitchenFridge",
        "UniversityFridge",
        "WesternKitchenFridge",
    },

    -- =========================================================
    -- FREEZER
    -- Residential and commercial freezers
    -- =========================================================
    FREEZER = {
        "FreezerGeneric",
        "FreezerRich",
        "FreezerTrailerPark",
        "FreezerDrugLab",
        "FreezerFarmStorage",
        "FreezerGarage",
        "FreezerHoarder",
        "FreezerHunter",
        "FreezerFrozenFood",
        "FreezerIceCream",
        "CrateChestFreezer",
        "ArenaKitchenFreezer",
        "BakeryKitchenFreezer",
        "BurgerKitchenFreezer",
        "ButcherFreezer",
        "CafeteriaKitchenFreezer",
        "CatfishKitchenFreezer",
        "ChineseKitchenFreezer",
        "DeepFryKitchenFreezer",
        "DinerKitchenFreezer",
        "FishChipsKitchenFreezer",
        "ItalianKitchenFreezer",
        "JaysKitchenFreezer",
        "MexicanKitchenFreezer",
        "PizzaKitchenFreezer",
        "RestaurantKitchenFreezer",
        "SafehouseFreezer",
        "SafehouseFreezer_Mid",
        "SafehouseFreezer_Late",
        "SeafoodKitchenFreezer",
        "SpiffosKitchenFreezer",
        "SushiKitchenFreezer",
        "TheatreKitchenFreezer",
        "WesternKitchenFreezer",
    },

    -- =========================================================
    -- STOVE
    -- Residential and commercial stoves
    -- =========================================================
    STOVE = {
        "StoveGeneric",
        "StoveClassy",
        "StoveRedneck",
        "StoveSpiffos",
        "DerelictHouseStove",
        "SafehouseStove",
        "SafehouseStove_Mid",
        "SafehouseStove_Late",
        "WildWestWoodStove",
        "CrateAntiqueStove",
        "BakeryKitchenStove",
    },

    -- =========================================================
    -- KITCHEN
    -- Kitchens (utensils, dishes, basic storage)
    -- =========================================================
    KITCHEN = {
        "ArenaKitchenCutlery",
        "ArmyBunkerKitchen",
        "BakeryKitchenBaking",
        "BakeryKitchenCutlery",
        "BakeryKitchenStorage",
        "BurgerKitchenCutlery",
        "CafeKitchenSupplies",
        "ChineseKitchenBaking",
        "ChineseKitchenCutlery",
        "CrepeKitchenBaking",
        "ItalianKitchenBaking",
        "JaysKitchenBaking",
        "KitchenBaking",
        "KitchenBreakfast",
        "KitchenDishes",
        "KitchenPots",
        "KitchenRandom",
        "MexicanKitchenBaking",
        "MexicanKitchenButcher",
        "MexicanKitchenSauce",
        "PizzaKitchenBaking",
        "SpiffosKitchenBaking",
        "SpiffosKitchenSpecial",
        "StoreKitchenBaking",
        "StoreKitchenCutlery",
        "StoreKitchenPots",
        "SushiKitchenBaking",
        "SushiKitchenCutlery",
        "WesternKitchenBaking",
        "WildWestKitchen",
        "BakeryKitchenTrays",
        "CafeKitchenMugs",
        "CafeteriaKitchenLaundry",
        "CrateDishes",
        "DishCabinetGeneric",
        "DishCabinetLiquor",
        "DishCabinetVIPLounge",
        "DishwasherGeneric",
        "JaysKitchenBags",
        "KitchenBook",
        "KitchenMicrowave",
        "KnifeFactoryCutlery",
        "KnifeFactoryKitchenKnife",
        "KnifeFactoryKitchenKnifeBlades",
        "KnifeStoreCutlery",
        "SpiffosKitchenBags",
        "SpiffosKitchenCups",
        "SpiffosKitchenTrays",
        "StoreKitchenBags",
        "StoreKitchenCleaning",
        "StoreKitchenCups",
        "StoreKitchenGlasses",
        "StoreKitchenPotatoes",
        "StoreKitchenTrays",
    },

    -- =========================================================
    -- KITCHEN_SAUCES
    -- Kitchens (sauces, meats, specific goods)
    -- =========================================================
    KITCHEN_SAUCES = {
        "ArenaKitchenSauce",
        "BurgerKitchenSauce",
        "BurgerKitchenButcher",
        "CafeKitchenCoffee",
        "CatfishKitchenButcher",
        "ChineseKitchenSauce",
        "ChineseKitchenButcher",
        "DinerBackRoomCounter",
        "FishChipsKitchenSauce",
        "FishChipsKitchenButcher",
        "ItalianKitchenSauce",
        "ItalianKitchenButcher",
        "JaysKitchenSauce",
        "JaysKitchenButcher",
        "KitchenBottles",
        "KitchenCannedFood",
        "KitchenDryFood",
        "PizzaKitchenSauce",
        "PizzaKitchenButcher",
        "PizzaKitchenCheese",
        "SeafoodKitchenSauce",
        "SeafoodKitchenButcher",
        "SpiffosKitchenSauce",
        "SpiffosKitchenButcher",
        "StoreKitchenSauce",
        "StoreKitchenButcher",
        "StoreKitchenCafe",
        "StoreKitchenDishes",
        "SushiKitchenSauce",
        "SushiKitchenButcher",
        "WesternKitchenSauce",
        "WesternKitchenButcher",
        "ButcherChicken",
        "ButcherChops",
        "ButcherFish",
        "ButcherGround",
        "ButcherLiterature",
        "ButcherSmoked",
        "ButcherSnacks",
        "ButcherSpices",
        "ButcherTools",
        "CafeKitchenTea",
        "CrepeKitchenSauce",
    },

    -- =========================================================
    -- CAFETERIA
    -- Cafeterias and dining spaces
    -- =========================================================
    CAFETERIA = {
        "CafeteriaDrinks",
        "CafeteriaSnacks",
        "CafeteriaFruit",
        "CafeteriaSandwiches",
        "CafeteriaTrays",
    },

    -- =========================================================
    -- SAFEHOUSE_FOOD
    -- Shelters (food and supplies, includes mid/late phases)
    -- =========================================================
    SAFEHOUSE_FOOD = {
        "SafehouseFood",
        "SafehouseFood_Mid",
        "SafehouseFood_Late",
    },


    -- =========================================================
    -- AMMO
    -- Ammunition and reloading supplies
    -- =========================================================
    AMMO = {
        "ArmyStorageAmmunition",
        "ArmySurplusAmmoBoxes",
        "GunStoreAmmunition",
        "GunStoreMagsAmmo",
        "PoliceStorageAmmunition",
        "SWATStorageAmmunition",
    },

    -- =========================================================
    -- BOOKS
    -- Books, literature, magazines and libraries
    -- =========================================================
    BOOKS = {
        "AnthropologyBooks",
        "ArmySurplusLiterature",
        "ArtStoreLiterature",
        "BookStoreCounter",
        "BookstoreArt",
        "BookstoreAutomotive",
        "BookstoreBags",
        "BookstoreBiography",
        "BookstoreBlueCollar",
        "BookstoreBooks",
        "BookstoreBusiness",
        "BookstoreChilds",
        "BookstoreCinema",
        "BookstoreCooking",
        "BookstoreCrafts",
        "BookstoreCrimeFiction",
        "BookstoreFantasySciFi",
        "BookstoreFarming",
        "BookstoreGeneralReference",
        "BookstoreHistory",
        "BookstoreHobbies",
        "BookstoreHorror",
        "BookstoreLegal",
        "BookstoreLiteraryFiction",
        "BookstoreMilitaryHistory",
        "BookstoreMisc",
        "BookstoreNewAge",
        "BookstoreNonFiction",
        "BookstoreOccult",
        "BookstoreOutdoors",
        "BookstorePersonal",
        "BookstorePhilosophy",
        "BookstorePolitics",
        "BookstoreReligion",
        "BookstoreRomance",
        "BookstoreSchoolTextbook",
        "BookstoreScience",
        "BookstoreSports",
        "BookstoreStationery",
        "BookstoreThriller",
        "BookstoreTravel",
        "BookstoreWestern",
        "CafeShelfBooks",
        "CampingStoreBooks",
        "ClockRepairLiterature",
        "ComicStoreCounter",
        "ComicStoreDisplayBooks",
        "ComicStoreDisplayComics",
        "ComicStoreDisplayDice",
        "ComicStoreMagazines",
        "ComicStoreShelfComics",
        "ComicStoreShelfFantasy",
        "ComicStoreShelfGames",
        "ComicStoreShelfSciFi",
        "CortmanOfficeBooks",
        "CrateBooks",
        "CrateBooksSchool",
        "CrateComics",
        "CrateMagazines",
        "CrateNewspapers",
        "CrateNewspapersNew",
        "GigamartLiterature",
        "GolfStoreLiterature",
        "HomeCinemaLiterature",
        "KnappingBooks",
        "LaboratoryBooks",
        "LibraryArt",
        "LibraryBiography",
        "LibraryBooks",
        "LibraryBusiness",
        "LibraryChilds",
        "LibraryCinema",
        "LibraryCounter",
        "LibraryCrimeFiction",
        "LibraryFantasySciFi",
        "LibraryGeneralReference",
        "LibraryHistory",
        "LibraryHorror",
        "LibraryLegal",
        "LibraryLiteraryFiction",
        "LibraryMagazines",
        "LibraryMilitaryHistory",
        "LibraryNewAge",
        "LibraryNonFiction",
        "LibraryOccult",
        "LibraryOutdoors",
        "LibraryPersonal",
        "LibraryPhilosophy",
        "LibraryPolitics",
        "LibraryReligion",
        "LibraryRomance",
        "LibraryScience",
        "LibrarySports",
        "LibraryThriller",
        "LibraryTravel",
        "LibraryWestern",
        "LiquorStoreMagazineRack",
        "MagazineRackAdult",
        "MagazineRackBrochure",
        "MagazineRackCards",
        "MagazineRackFancy",
        "MagazineRackMaps",
        "MagazineRackMixed",
        "MagazineRackNewspaper",
        "MagazineRackPaperback",
        "MayorWestPointBooks",
        "MedievalBooks",
        "OutdoorSupplyMagazines",
        "PlankStashMagazine",
        "PoliceLibraryLegal",
        "PostOfficeBooks",
        "PostOfficeMagazines",
        "PostOfficeNewspapers",
        "PotteryBooks",
        "RangerBooks",
        "RangerMagazines",
        "SafehouseBookShelf",
        "SalonMagazines",
        "TailoringLiterature",
        "TheatreLiterature",
        "UniversityLibraryArt",
        "UniversityLibraryBiography",
        "UniversityLibraryBooks",
        "UniversityLibraryBusiness",
        "UniversityLibraryCinema",
        "UniversityLibraryGeneralReference",
        "UniversityLibraryHistory",
        "UniversityLibraryLegal",
        "UniversityLibraryMagazines",
        "UniversityLibraryMilitaryHistory",
        "UniversityLibraryPhilosophy",
        "UniversityLibraryPolitics",
        "UniversityLibraryScience",
        "UniversityLibrarySports",
    },

    -- =========================================================
    -- CLOTHING
    -- Clothing, footwear, headwear and outfits (stores, wardrobes)
    -- =========================================================
    CLOTHING = {
        "AmbulanceDriverOutfit",
        "AnthropologyDisplayClothing",
        "ArmyHangarOutfit",
        "ArmySurplusCots",
        "ArmySurplusFootwear",
        "ArmySurplusHeadwear",
        "ArmySurplusOutfit",
        "BackstageClothingRack",
        "BackstageDresser",
        "BandMerchClothes",
        "BandPracticeClothing",
        "BedroomDresser",
        "BedroomDresserChild",
        "BedroomDresserClassy",
        "BedroomDresserRedneck",
        "BookstoreFashion",
        "BowlingAlleyShoes",
        "BoxingStorageGloves",
        "BoxingStorageHelmets",
        "CampingStoreClothes",
        "CampingStoreLegwear",
        "CarSupplyGloves",
        "CarpenterOutfit",
        "ChefOutfit",
        "ClothingPoor",
        "ClothingRack",
        "ClothingStorageAllJackets",
        "ClothingStorageAllShirts",
        "ClothingStorageFootwear",
        "ClothingStorageHeadwear",
        "ClothingStorageLegwear",
        "ClothingStorageWinter",
        "ClothingStoresBoots",
        "ClothingStoresDress",
        "ClothingStoresEyewear",
        "ClothingStoresGloves",
        "ClothingStoresGlovesLeather",
        "ClothingStoresHeadwear",
        "ClothingStoresHolsters",
        "ClothingStoresJackets",
        "ClothingStoresJacketsFormal",
        "ClothingStoresJacketsLeather",
        "ClothingStoresJeans",
        "ClothingStoresJumpers",
        "ClothingStoresOvershirts",
        "ClothingStoresPants",
        "ClothingStoresPantsFormal",
        "ClothingStoresPantsLeather",
        "ClothingStoresShirts",
        "ClothingStoresShirtsFormal",
        "ClothingStoresShoes",
        "ClothingStoresShoesLeather",
        "ClothingStoresSocks",
        "ClothingStoresSport",
        "ClothingStoresSummer",
        "ClothingStoresUnderwearMan",
        "ClothingStoresUnderwearWoman",
        "ClothingStoresWoman",
        "ConstructionWorkerOutfit",
        "CrateBootsArmy",
        "CrateBootsArmyDesert",
        "CrateBootsOld",
        "CrateClothesRandom",
        "CrateCostume",
        "CrateFootwearRandom",
        "CultistClothing",
        "DoctorOutfit",
        "DresserGeneric",
        "DrugLabOutfit",
        "ElectricianOutfit",
        "FarmerOutfit",
        "FireStorageOutfit",
        "FiremanOutfit",
        "FishermanOutfit",
        "GardenerOutfit",
        "GolfStoreClothingRack",
        "HospitalRoomWardrobe",
        "JewelryWeddingRings",
        "LaundrySuits",
        "LibraryFashion",
        "LingerieStoreAccessories",
        "LingerieStoreBras",
        "LingerieStoreOutfits",
        "LingerieStoreUnderwear",
        "LivingRoomWardrobe",
        "LostAndFoundClothing",
        "MechanicOutfit",
        "MechanicShelfOutfit",
        "MedicalClinicOutfit",
        "MedicalStorageOutfit",
        "MetalWorkerOutfit",
        "MorgueOutfit",
        "NurseOutfit",
        "OutdoorSupplyBoots",
        "OutdoorSupplyClothes",
        "PoliceOutfit",
        "PoliceStateOutfit",
        "PoliceStorageArmor",
        "PoliceStorageOutfit",
        "PrisonStorageArmor",
        "RangerOutfit",
        "SWATStorageArmor",
        "SportStorageHelmets",
        "StripClubDressers",
        "ToolStoreFootwear",
        "ToolStoreOutfit",
        "UniversityDesk_Fashion",
        "UniversityFilingCabinet_Fashion",
        "UniversityWardrobe",
        "WardrobeChild",
        "WardrobeClassy",
        "WardrobeGeneric",
        "WardrobeRedneck",
        "WeddingStoreDresses",
        "WeddingStoreSuits",
        "WildWestClothing",
        "ZippeeClothing",
    },

    -- =========================================================
    -- FARMING
    -- Gardening, farming and homesteading
    -- =========================================================
    FARMING = {
        "BeerGardenCounter",
        "CrateAnimalFeed",
        "CrateFertilizer",
        "CrateGardening",
        "CrateSunflowerSeeds",
        "Homesteading",
    },

    -- =========================================================
    -- FIREARMS
    -- Firearms and gun stores
    -- =========================================================
    FIREARMS = {
        "ArmyStorageGuns",
        "DrugLabGuns",
        "FirearmWeapons",
        "FirearmWeapons_Late",
        "FirearmWeapons_Mid",
        "GarageFirearms",
        "GunStoreAccessories",
        "GunStoreBodyArmor",
        "GunStoreDisplayCase",
        "GunStoreGuns",
        "GunStoreKnives",
        "GunStoreLiterature",
        "GunStoreMagazineRack",
        "GunStorePistols",
        "GunStoreRifles",
        "GunStoreShelf",
        "GunStoreShotguns",
        "PawnShopGuns",
        "PawnShopGunsSpecial",
        "PlankStashGun",
        "PoliceStorageGuns",
        "PrisonArmoryShotguns",
        "PrisonStorageGuns",
        "RangerStorageGuns",
        "SWATStorageGuns",
    },

    -- =========================================================
    -- FURNITURE
    -- Furniture and home decor
    -- =========================================================
    FURNITURE = {
        "BedroomSidetable",
        "BedroomSidetableChild",
        "BedroomSidetableClassy",
        "BedroomSidetableRedneck",
        "ChangeroomCounters",
        "ClosetShelfGeneric",
        "ControlRoomCounter",
        "CrateBlueComfyChair",
        "CrateBluePlasticChairs",
        "CrateBlueRattanChair",
        "CrateBrownComfyChair",
        "CrateBrownLowTables",
        "CrateDarkBlueChairs",
        "CrateDarkWoodenChairs",
        "CrateFancyBlackChairs",
        "CrateFancyDarkTables",
        "CrateFancyLowTables",
        "CrateFancyWhiteChairs",
        "CrateFoldingChairs",
        "CrateGreenChairs",
        "CrateGreenComfyChair",
        "CrateGreyChairs",
        "CrateGreyComfyChair",
        "CrateLightRoundTable",
        "CrateLinens",
        "CrateLongTables",
        "CrateMannequins",
        "CrateOakRoundTable",
        "CrateOrangeModernChair",
        "CratePlasticChairs",
        "CratePlasticLowTables",
        "CratePurpleRattanChair",
        "CratePurpleWoodenChairs",
        "CrateRedChairs",
        "CrateRedWoodenChairs",
        "CrateRoundTable",
        "CrateSkeletonDisplay",
        "CrateSmallTables",
        "CrateWhiteComfyChair",
        "CrateWhiteSimpleChairs",
        "CrateWhiteWoodenChairs",
        "CrateWoodenChairs",
        "CrateWoodenStools",
        "CrateYellowModernChair",
        "GigamartBedding",
        "LivingRoomShelf",
        "LivingRoomShelfClassy",
        "LivingRoomShelfNoTapes",
        "LivingRoomShelfRedneck",
        "LivingRoomSideTable",
        "LivingRoomSideTableClassy",
        "LivingRoomSideTableNoRemote",
        "LivingRoomSideTableRedneck",
        "LockerArmyBedroom",
        "LockerArmyBedroomHome",
        "MotelLinens",
        "MotelSideTable",
        "RecRoomShelf",
        "StudioPropShelf",
        "UniversitySideTable",
        "WallDecor",
        "WildWestBedroom",
        "WildWestLivingRoom",
    },

    -- =========================================================
    -- GROCERY
    -- Food, groceries and general provisions
    -- =========================================================
    GROCERY = {
        "BBQCharcoal",
        "BBQCharcoalRich",
        "BBQPropane",
        "BBQPropaneRich",
        "BakeryBread",
        "BakeryCake",
        "BakeryDoughnuts",
        "BakeryMisc",
        "BakeryPie",
        "CandyStoreSnacks",
        "CrateBlackBBQ",
        "CrateBunsBurger",
        "CrateBunsHotdog",
        "CrateButter",
        "CrateCandyPackage",
        "CrateCannedFood",
        "CrateCannedFoodSpoiled",
        "CrateCannedTomato",
        "CrateCereal",
        "CrateCharcoal",
        "CrateChips",
        "CrateChocolate",
        "CrateChocolateChips",
        "CrateCigarettes",
        "CrateCocoaPowder",
        "CrateCoffee",
        "CrateCondiments",
        "CrateCrackers",
        "CrateFlour",
        "CrateFountainCups",
        "CrateGrahamCrackers",
        "CrateGum",
        "CrateMacaroni",
        "CrateMapleSyrup",
        "CrateMarinara",
        "CrateMarshmallows",
        "CrateMetalPipes",
        "CrateOilVegetable",
        "CratePasta",
        "CratePeanuts",
        "CratePopcorn",
        "CratePropane",
        "CrateRedBBQ",
        "CrateRiceVinegar",
        "CrateSeaweed",
        "CrateSugar",
        "CrateSugarBrown",
        "CrateTacoShells",
        "CrateTortillaChips",
        "CrateYeast",
        "FoodGourmet",
        "GigamartCandy",
        "GigamartCannedFood",
        "GigamartCrisps",
        "GigamartSauce",
        "GigamartSpices",
        "GrillAcessories",
        "GroceryStandFruits1",
        "GroceryStandFruits2",
        "GroceryStandFruits3",
        "GroceryStandLettuce",
        "GroceryStandVegetables1",
        "GroceryStandVegetables2",
        "GroceryStandVegetables3",
        "GroceryStandVegetables4",
        "GroceryStandVegetables5",
        "HotdogStandDrinks",
        "HotdogStandToppings",
        "JuiceStandDrinks",
        "JuiceStandSnacks",
        "MayorWestPointSafe",
        "Meat",
        "ProduceStorageApples",
        "ProduceStorageBellPeppers",
        "ProduceStorageBroccoli",
        "ProduceStorageCabbages",
        "ProduceStorageCarrots",
        "ProduceStorageCauliflower",
        "ProduceStorageCherry",
        "ProduceStorageCorn",
        "ProduceStorageEggplant",
        "ProduceStorageEquipment",
        "ProduceStorageGrapes",
        "ProduceStorageGreenpeas",
        "ProduceStorageKale",
        "ProduceStorageLeeks",
        "ProduceStorageLettuce",
        "ProduceStorageLooseFruit",
        "ProduceStorageLooseVeg",
        "ProduceStorageOnions",
        "ProduceStoragePeaches",
        "ProduceStoragePears",
        "ProduceStoragePotatoes",
        "ProduceStorageRadishes",
        "ProduceStorageRottenFruit",
        "ProduceStorageRottenVeg",
        "ProduceStorageStrawberries",
        "ProduceStorageSweetPotatoes",
        "ProduceStorageTomatoes",
        "ProduceStorageWatermelons",
        "ServingTrayBiscuits",
        "ServingTrayBurgers",
        "ServingTrayBurritos",
        "ServingTrayChicken",
        "ServingTrayChickenFried",
        "ServingTrayChickenNuggets",
        "ServingTrayChickenWings",
        "ServingTrayCornbread",
        "ServingTrayFish",
        "ServingTrayFishFingers",
        "ServingTrayFishFried",
        "ServingTrayFries",
        "ServingTrayGravy",
        "ServingTrayHam",
        "ServingTrayHotdogs",
        "ServingTrayLobster",
        "ServingTrayMaki",
        "ServingTrayMeatDumplings",
        "ServingTrayMeatSteamBuns",
        "ServingTrayMussels",
        "ServingTrayNoodleSoup",
        "ServingTrayOmelettes",
        "ServingTrayOnigiri",
        "ServingTrayOnionRings",
        "ServingTrayOysters",
        "ServingTrayOystersFried",
        "ServingTrayPancakes",
        "ServingTrayPerogies",
        "ServingTrayPie",
        "ServingTrayPizza",
        "ServingTrayPorkChops",
        "ServingTrayPotatoPancakes",
        "ServingTrayRefriedBeans",
        "ServingTraySalmon",
        "ServingTraySausage",
        "ServingTrayScrambledEggs",
        "ServingTrayShrimp",
        "ServingTrayShrimpDumplings",
        "ServingTrayShrimpFried",
        "ServingTraySpringRolls",
        "ServingTraySteak",
        "ServingTraySushiEgg",
        "ServingTraySushiFish",
        "ServingTrayTaco",
        "ServingTrayTatoDots",
        "ServingTrayTofuFried",
        "ServingTrayWaffles",
        "SmokingRoomCigars",
        "SmokingRoomPipes",
        "StoreCounterTobacco",
        "StoreShelfBBQ",
        "StoreShelfSnacks",
        "StoreShelfSpices",
        "TheatrePopcorn",
        "TobaccoStoreAccessories",
        "TobaccoStoreChew",
        "TobaccoStoreCigarettes",
        "TobaccoStoreCigarillos",
        "TobaccoStoreCigars",
        "TobaccoStorePipes",
    },

    -- =========================================================
    -- HOBBY
    -- Arts, crafts and hobby supplies
    -- =========================================================
    HOBBY = {
        "Antiques",
        "ArtStorePottery",
        "ArtSupplies",
        "CrateFabric_Cotton",
        "CrateFabric_DenimBlack",
        "CrateFabric_DenimBlue",
        "CrateFabric_DenimDarkBlue",
        "CratePottery",
        "CrateTailoring",
        "Hobbies",
        "ImprovisedCrafts",
        "SewingStoreFabric",
    },

    -- =========================================================
    -- HYGIENE
    -- Bathroom, cosmetics, cleaning and laundry
    -- =========================================================
    HYGIENE = {
        "BarLaundry",
        "BathroomCabinet",
        "BathroomCounter",
        "BathroomCounterEmpty",
        "BathroomCounterMotel",
        "BathroomCounterNoMeds",
        "BathroomShelf",
        "BinBathroom",
        "CrateFancyToilets",
        "CrateSalonSupplies",
        "CrateToiletPaper",
        "DryerEmpty",
        "FossoilCounterCleaning",
        "Gas2GoCounterCleaning",
        "GasStoreCounterCleaning",
        "GasStoreToiletries",
        "GigamartBathing",
        "GigamartCleaning",
        "GigamartCosmetics",
        "GigamartToiletries",
        "JanitorCleaning",
        "LaundryCleaning",
        "LaundryLoad1",
        "LaundryLoad2",
        "LaundryLoad3",
        "LaundryLoad4",
        "LaundryLoad5",
        "LaundryLoad6",
        "LaundryLoad7",
        "LaundryLoad8",
        "MotelTowels",
        "PoliceLaundry",
        "PrisonLaundry",
        "SafehouseDryer",
        "SafehouseWasher",
        "SalonCounter",
        "SalonShelfHaircare",
        "SalonShelfTowels",
        "StoreCounterCleaning",
        "StripClubCosmetic",
        "WildWestBarberCounter",
        "WildWestBarberShelves",
    },

    -- =========================================================
    -- JEWELRY
    -- Jewelry and precious goods
    -- =========================================================
    JEWELRY = {
        "DepartmentStoreJewelry",
        "JewelryGems",
        "JewelryGold",
        "JewelryNavelRings",
        "JewelryOthers",
        "JewelrySilver",
        "JewelryStorageAll",
        "JewelryWrist",
    },

    -- =========================================================
    -- LIQUOR
    -- Liquor, wine and beer
    -- =========================================================
    LIQUOR = {
        "BarCounterLiquor",
        "BreweryBottles",
        "BreweryCans",
        "BreweryHops",
        "CrateLiquor",
        "CrateSodaBottles",
        "GigamartBottles",
        "LiquorStoreBags",
        "LiquorStoreBeer",
        "LiquorStoreBeerFancy",
        "LiquorStoreBrandy",
        "LiquorStoreGin",
        "LiquorStoreMix",
        "LiquorStoreRum",
        "LiquorStoreScotch",
        "LiquorStoreTequila",
        "LiquorStoreVodka",
        "LiquorStoreWhiskey",
        "LiquorStoreWine",
        "LiquorStoreWineFancy",
        "SafehouseBooze",
        "StoreShelfWhiskey",
        "WhiskeyBottlingFull",
    },

    -- =========================================================
    -- MATERIALS
    -- Building and raw materials
    -- =========================================================
    MATERIALS = {
        "BagStoreLeather",
        "CrateClayBricks",
        "CrateConcrete",
        "CrateGravelBags",
        "CrateHeavyChains",
        "CrateLeather",
        "CrateLeatherLarge",
        "CrateLimestoneCrushed",
        "CrateLumber",
        "CrateMasonry",
        "CratePlaster",
        "CrateSheetMetal",
        "CrateWallFinish",
        "PlumbingSupplies",
    },

    -- =========================================================
    -- MEDIA
    -- Music, film, photography and instruments
    -- =========================================================
    MEDIA = {
        "BackstageCounter",
        "BackstageLockers",
        "BackstageRigging",
        "BandMerchShelves",
        "BandPracticeInstruments",
        "BookstoreMusic",
        "CameraStoreDisplayCase",
        "CameraStoreShelves",
        "ClosetInstruments",
        "CrateCameraFilm",
        "CrateCompactDiscs",
        "CrateInstruments",
        "CratePhotos",
        "CrateVHSTapes",
        "HomeCinemaFilm",
        "LibraryMusic",
        "MovieRentalShelves",
        "MusicSchoolCases",
        "MusicSchoolDesk",
        "MusicSchoolLocker",
        "MusicSchoolSheets",
        "MusicStoreBass",
        "MusicStoreBrass",
        "MusicStoreCDs",
        "MusicStoreCases",
        "MusicStoreDrums",
        "MusicStoreGuitar",
        "MusicStoreLiterature",
        "MusicStoreOthers",
        "MusicStoreSpeaker",
        "MusicStoreStringed",
        "Photographer",
        "UniversityDesk_Music",
        "UniversityFilingCabinet_Music",
        "UniversityLibraryMusic",
    },

    -- =========================================================
    -- OFFICE
    -- Office supplies, desks and filing
    -- =========================================================
    OFFICE = {
        "AnthropologyDesk",
        "BankDeposit",
        "ClassroomDesk",
        "ClassroomSecondaryDesk",
        "CortmanOfficeDesk",
        "CortmanOfficeSidetable",
        "CrateOfficeChairs",
        "DaycareDesk",
        "DeskGeneric",
        "FilingCabinetGeneric",
        "JackiesDesk",
        "KidsDesk",
        "MayorWestPointDesk",
        "NolansDesk",
        "NolansFilingCabinet",
        "OfficeCounter",
        "OfficeDesk",
        "OfficeDeskHome",
        "OfficeDeskHomeClassy",
        "OfficeDeskSecretary",
        "OfficeDeskStressed",
        "OfficeDrawers",
        "PoliceCaptainDesk",
        "PoliceDesk",
        "PoliceFileBox",
        "PoliceFilingCabinet",
        "PostOfficeParcels",
        "PostOfficeSupplies",
        "RangerDesk",
        "SecurityDesk",
        "SpiffosDesk",
        "UniversityDesk_Anthropology",
        "UniversityDesk_Art",
        "UniversityDesk_Business",
        "UniversityDesk_Cinema",
        "UniversityDesk_Electrical",
        "UniversityDesk_Engineering",
        "UniversityDesk_English",
        "UniversityDesk_Glassmaking",
        "UniversityDesk_History",
        "UniversityDesk_Legal",
        "UniversityDesk_Math",
        "UniversityDesk_Medieval",
        "UniversityDesk_Nature",
        "UniversityDesk_Occult",
        "UniversityDesk_Philosophy",
        "UniversityDesk_Pioneer",
        "UniversityDesk_Politics",
        "UniversityDesk_Religion",
        "UniversityDesk_Science",
        "UniversityDesk_Therapy",
        "UniversityFilingCabinet_Art",
        "UniversityFilingCabinet_Business",
        "UniversityFilingCabinet_Cinema",
        "UniversityFilingCabinet_Engineering",
        "UniversityFilingCabinet_English",
        "UniversityFilingCabinet_Glassmaking",
        "UniversityFilingCabinet_History",
        "UniversityFilingCabinet_Legal",
        "UniversityFilingCabinet_Math",
        "UniversityFilingCabinet_Medieval",
        "UniversityFilingCabinet_Nature",
        "UniversityFilingCabinet_Occult",
        "UniversityFilingCabinet_Philosophy",
        "UniversityFilingCabinet_Politics",
        "UniversityFilingCabinet_Religion",
        "UniversityFilingCabinet_Science",
        "UniversityFilingCabinet_Therapy",
        "WaitingRoomDesk",
        "WildWestSheriffDesk",
    },

    -- =========================================================
    -- PET
    -- Pet supplies and pet food
    -- =========================================================
    PET = {
        "CratePetSupplies",
        "PetShopShelf",
    },

    -- =========================================================
    -- RELIGION
    -- Churches and religious items
    -- =========================================================
    RELIGION = {
        "ChurchStorageMisc",
        "CrateBibles",
    },

    -- =========================================================
    -- SCHOOL
    -- Schools and universities
    -- =========================================================
    SCHOOL = {
        "ClassroomMisc",
        "ClassroomSecondaryMisc",
        "ClassroomSecondaryShelves",
        "ClassroomShelves",
        "GigamartSchool",
        "SchoolLab",
        "SchoolLockersBad",
        "UniversityStorageAnthropology",
        "UniversityStorageScience",
    },

    -- =========================================================
    -- SCIENCE
    -- Science, labs and museums
    -- =========================================================
    SCIENCE = {
        "AnthropologyCounter",
        "AnthropologyDisplayWeapons",
        "Chemistry",
        "JanitorChemicals",
        "LaboratoryLockers",
        "MedievalAlchemy",
        "MedievalBible",
        "MedievalCooking",
        "MorgueChemicals",
        "ScienceMisc",
        "TestingLab",
    },

    -- =========================================================
    -- SPORTS
    -- Sporting goods and fitness equipment
    -- =========================================================
    SPORTS = {
        "BaseballLockers",
        "BaseballStoreShelves",
        "BowlingAlleyCounters",
        "BowlingAlleyLockers",
        "BowlingAlleyPins",
        "BoxingLockers",
        "BoxingMemorabilia",
        "CarnivalPrizes",
        "ClosetSportsEquipment",
        "CrateBaseballs",
        "CrateBasketballs",
        "CrateFitnessWeights",
        "CrateFootballs",
        "CrateGolfBalls",
        "CrateGolfClubs",
        "CrateSoccerBalls",
        "CrateSports",
        "FitnessTrainer",
        "GolfLockers",
        "GolfStorage",
        "GolfStoreAccessories",
        "GolfStoreBags",
        "GymLaundry",
        "GymLockers",
        "GymMats",
        "GymSweatbands",
        "GymTowels",
        "GymWeights",
        "SchoolGymSportsGear",
        "SportStorageBalls",
        "SportStorageBats",
        "SportStoragePaddles",
        "SportStorageRacquets",
        "SportStorageSticks",
        "SportStorageWeights",
        "SportStoreAccessories",
        "SportStoreBadminton",
        "SportStoreBaseball",
        "SportStoreBoxing",
        "SportStoreFootball",
        "SportStoreGolf",
        "SportStoreIceHockey",
        "SportStorePadding",
        "SportStoreSneakers",
        "SportStoreTennis",
    },

    -- =========================================================
    -- TOYS
    -- Toys and games
    -- =========================================================
    TOYS = {
        "DaycareCounter",
        "DaycareShelves",
    },

    -- =========================================================
    -- TRASH
    -- Bins, dumpsters and junk
    -- =========================================================
    TRASH = {
        "BinBar",
        "BinCrepe",
        "BinDumpster",
        "BinFireStation",
        "BinGeneric",
        "BinJays",
        "BinSpiffos",
        "BreweryEmptyBottles",
        "BreweryEmptyCans",
        "CrateEmptyBottles1",
        "CrateEmptyBottles2",
        "CrateEmptyMixed",
        "CrateEmptyTinCans",
        "CrateRandomJunk",
        "DerelictHouseJunk",
        "Empty",
        "JunkBin",
        "JunkHoard",
        "ProduceStorageEmptyBoxes",
        "WhiskeyBottlingEmpty",
    },

    -- =========================================================
    -- WEAPONS
    -- Melee and improvised weapons
    -- =========================================================
    WEAPONS = {
        "MedievalWeapons",
        "MedievalWeaponsJapan",
        "MeleeWeapons",
        "MeleeWeapons_Late",
        "MeleeWeapons_Mid",
    },

    -- =========================================================
    -- OTHER
    -- Miscellaneous / uncategorized containers
    -- =========================================================
    OTHER = {
        "CafeCounterMix",
        "ClockRepairWatches",
        "JanitorMisc",
        "JaysDiningCounter",
        "JudgeMattHassCounter",
        "LostAndFoundItems",
        "OtherGeneric",
        "RandomFiller",
        "RestaurantMenus",
        "ShelfGeneric",
        "SpaCabinet",
        "SpaCounter",
        "SpiffosDiningCounter",
        "VacationStuff",
        "WoodcraftDudeCounter",
    },

}

-- ==========================================================================
-- COMBINED GROUPS
-- A combo expands to the union of several KRCore.LOC groups (automatic dedupe
-- in KRCore_Server). Used with the same name in dist.add():
--     KRCore.dist.add("Base.MyItem", { POWER = 0.2 })
-- ==========================================================================

KRCore.COMBO = {

    -- Electronics + mechanic shops: everything power-, battery- and
    -- appliance-related (ideal for KR SolarOS)
    POWER = { "ELECTRONIC", "MECHANIC" },

    -- Military + survival: field gear (ideal for KR TacticalOS)
    TACTICAL = { "MILITARY", "SURVIVAL" },

    -- Fridges + freezers: all cold storage (ideal for KR FoodOS)
    COLD_STORAGE = { "FRIDGE", "FREEZER" },

    -- Kitchens + stoves: the whole cooking environment
    COOKING = { "KITCHEN", "STOVE" },

    -- Full military looting: bases, guns, melee weapons and ammo (ideal for KR TacticalOS)
    WARZONE = { "MILITARY", "FIREARMS", "WEAPONS", "AMMO" },

    -- All food storage: groceries plus cold storage (ideal for KR FoodOS)
    FOOD = { "GROCERY", "FRIDGE", "FREEZER" },

    -- Tools, auto parts and building materials (ideal for crafting/tool mods)
    WORKSHOP = { "INDUSTRIAL", "MECHANIC", "MATERIALS" },

}
